name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Capacitor CLI
      run: npm install @capacitor/cli @capacitor/core --save

    - name: Build Vite project
      run: npm run build

    - name: Initialize Capacitor if needed
      run: |
        npx cap init "AAAApp" "com.example.aaa" --web-dir=dist || echo "Already initialized"

    - name: Add Android platform if missing
      run: |
        npx cap add android || echo "Android platform exists"

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build APK
      working-directory: android
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
