name: Build APK from Vite + Capacitor

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Pobranie repo
    - uses: actions/checkout@v3

    # 2️⃣ Instalacja Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # 3️⃣ Instalacja zależności projektu
    - name: Install project dependencies
      run: npm install

    # 4️⃣ Instalacja Capacitor CLI i Core
    - name: Install Capacitor
      run: npm install @capacitor/core @capacitor/cli --save-dev

    # 5️⃣ Budowa frontend Vite
    - name: Build Vite
      run: npm run build

    # 6️⃣ Kopiowanie build do Androida
    - name: Copy build to Android
      run: |
        npx cap copy
        npx cap sync android

    # 7️⃣ Sprawdzenie zawartości www
    - name: Check www folder
      run: ls -R android/app/src/main/assets/www

    # 8️⃣ Instalacja JDK 11
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # 9️⃣ Budowa APK release
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease

    # 🔍 Znalezienie APK (signed lub unsigned)
    - name: Find APK file
      run: |
        find android/app/build/outputs/apk/ -type f -name "*.apk"

    # 🔄 Upload APK jako artefakt
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/**/*.apk
