name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # 1. Pobranie repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalacja Node.js (potrzebne do Capacitor sync)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Instalacja zależności webowych (dla Capacitor)
      - name: Install NPM dependencies
        run: npm install

      # 4. Synchronizacja Capacitor (kopiuje build Vite do Androida)
      - name: Capacitor sync
        run: npx cap sync android

      # 5. Instalacja JDK (wymagane do Gradle)
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 6. Build APK
      - name: Build APK
        working-directory: android
        run: ./gradlew assembleDebug

      # 7. Upload APK jako artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
