name: Build Vite Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Pobranie repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Instalacja Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # Instalacja zależności
    - name: Install dependencies
      run: npm install

    # Budowa projektu Vite
    - name: Build Vite
      run: npm run build

    # Upload folderu build/dist jako artefakt
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vite-build
        path: dist/
